

import Navbar from "@/componets/Navbar";
import Hero from "@/componets/Hero";
import Cards from "@/componets/cards";
import "./globals.css";



export const metadata = {
  title: "Siksha'O' Sahayog",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <Navbar />
        <Hero />
        <Cards />
        {children}
      </body>
    </html>
  );
}
